MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.14            # [osx and x86_64]
c_stdlib_version:    # [osx and x86_64]
  - 10.14            # [osx and x86_64]
channel_sources:
  - tiledb/label/for-cloud,conda-forge
channel_targets:
  - tiledb for-cloud
lz4_c:
  - 1.9.3
